## This code is import all LISST ASC. files and convert them to a readable format

Spring 2023

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os 

# identify the directory as the "Raw_LISST_files" folder
directory = "Raw_LISST_files/Spring_2023"

# make a list of all the files in the directory
files = os.listdir(directory)

# create a list to store DataFrames
dfs = []

# iterate over the files
for file in files:
    # check if the file is an ASC file
    if file.endswith('.ASC'):
        # read the file
        data = pd.read_csv(directory + '/' + file, delimiter=',', skiprows=3)
        # transpose the data
        data_transposed = data.transpose()
        # convert the second column to a numeric type
        data_transposed.iloc[:, 1] = pd.to_numeric(data_transposed.iloc[:, 1], errors='coerce')
        # convert the second column to a DataFrame and set the column name to the file name
        df = data_transposed.iloc[:, 1].to_frame(name=os.path.splitext(file)[0])
        # add the DataFrame to the list
        dfs.append(df)

# concatenate all the DataFrames in the list into a single DataFrame
spring2023 = pd.concat(dfs, axis=1)

In [38]:
# get rid of the last 20 rows
spring2023 = spring2023[:-20]
# get rid of the first 21 rows
spring2023 = spring2023[21:]

In [3]:
spring2023

,SP2301,SP2302,SP2303,SP2304,SP2305,SP2306,SP2307,SP2308,SP2309,SP2310,...,SP2390,SP2391,SP2392,SP2393,SP2394,SP2395,SP2396,SP2397,SP2398,SP2399
Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Optical Transmission,0.964,0.964,0.965,0.965,0.965,0.966,0.966,0.967,0.967,0.968,...,0.973,0.973,0.973,0.97,0.969,0.969,0.966,0.964,0.931,0.928
Total Volume Concentration,39.617,34.853,31.518,28.642,26.761,24.638,23.041,21.629,20.460,19.381,...,67.095,62.658,38.991,40.55,43.337,40.327,49.866,52.545,76.423,110.529
Total Mass Concentration,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Lref,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000
Lpwr,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000
Background Mixer,30.000,30.000,30.000,30.000,30.000,30.000,30.000,30.000,30.000,30.000,...,30.000,30.000,30.000,30.00,30.000,30.000,30.000,30.000,30.000,30.000
CPU Temperature,-1.000,-1.000,-1.000,-1.000,-1.000,-1.000,-1.000,-1.000,-1.000,-1.000,...,-1.000,-1.000,-1.000,-1.00,-1.000,-1.000,-1.000,-1.000,-1.000,-1.000
Display Temp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
# export as a csv file
spring2023.to_csv('Spring_2023.csv')

### Summer 2023

In [2]:
# identify the directory as the "Raw_LISST_files" folder
directory = "Raw_LISST_files/Summer_2023"

# make a list of all the files in the directory
files = os.listdir(directory)

# create a list to store DataFrames
dfs = []

# iterate over the files
for file in files:
    # check if the file is an ASC file
    if file.endswith('.ASC'):
        # read the file
        data = pd.read_csv(directory + '/' + file, delimiter=',', skiprows=3)
        # transpose the data
        data_transposed = data.transpose()
        # convert the second column to a numeric type
        data_transposed.iloc[:, 1] = pd.to_numeric(data_transposed.iloc[:, 1], errors='coerce')
        # convert the second column to a DataFrame and set the column name to the file name
        df = data_transposed.iloc[:, 1].to_frame(name=os.path.splitext(file)[0])
        # add the DataFrame to the list
        dfs.append(df)

# concatenate all the DataFrames in the list into a single DataFrame
summer2023 = pd.concat(dfs, axis=1)

In [41]:
# get rid of the last 20 rows
summer2023 = summer2023[:-20]
# get rid of the first 21 rows
summer2023 = summer2023[21:]

In [5]:
summer2023

,SMST101,SMST102,SMST103,SMST104,SMST105,SMST106,SMST107,SMST108,SMST109,SMST110,...,ST734,ST735,ST736,ST737,ST738,ST739,ST740,ST741,ST742,ST743
Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Optical Transmission,0.809,0.793,0.795,0.796,0.868,0.868,0.868,0.867,0.868,0.891,...,0.918,0.934,0.936,0.933,0.928,0.930,0.926,0.941,0.942,0.940
Total Volume Concentration,203.027,214.036,214.161,211.603,114.961,111.631,114.078,119.820,119.845,106.415,...,72.896,64.424,59.276,61.128,81.930,80.164,85.723,54.382,52.567,55.398
Total Mass Concentration,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Lref,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Lpwr,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Background Mixer,30.000,30.000,30.000,30.000,30.000,30.000,30.000,30.000,30.000,30.000,...,30.000,30.000,30.000,30.000,30.000,30.000,30.000,30.000,30.000,30.000
CPU Temperature,-1.000,-1.000,-1.000,-1.000,-1.000,-1.000,-1.000,-1.000,-1.000,-1.000,...,-1.000,-1.000,-1.000,-1.000,-1.000,-1.000,-1.000,-1.000,-1.000,-1.000
Display Temp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
# export as a csv file
summer2023.to_csv('Summer_2023.csv')

### Summer 2022

In [3]:
# identify the directory as the "Raw_LISST_files" folder
directory = "Raw_LISST_files/Summer_2022"

# make a list of all the files in the directory
files = os.listdir(directory)

# create a list to store DataFrames
dfs = []

# iterate over the files
for file in files:
    # check if the file is an ASC file
    if file.endswith('.ASC'):
        # read the file
        data = pd.read_csv(directory + '/' + file, delimiter=',', skiprows=3)
        # transpose the data
        data_transposed = data.transpose()
        # convert the second column to a numeric type
        data_transposed.iloc[:, 1] = pd.to_numeric(data_transposed.iloc[:, 1], errors='coerce')
        # convert the second column to a DataFrame and set the column name to the file name
        df = data_transposed.iloc[:, 1].to_frame(name=os.path.splitext(file)[0])
        # add the DataFrame to the list
        dfs.append(df)

# concatenate all the DataFrames in the list into a single DataFrame
summer2022 = pd.concat(dfs, axis=1)

In [4]:
# get rid of the last 20 rows
summer2023 = summer2023[:-20]
# get rid of the first 21 rows
summer2023 = summer2023[21:]

In [6]:
summer2022

,S22S101,S22S102,S22S103,S22S104,S22S105,S22S106,S22S107,S22S108,ST22201,ST22202,ST22203,ST22204,ST22205,ST22206,ST22207,ST32201
Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Optical Transmission,0.867,0.883,0.971,0.948,0.964,0.933,0.955,0.969,0.814,0.888,0.920,0.952,0.961,0.971,0.972,0.930
Total Volume Concentration,206.815,152.527,31.825,55.058,36.439,66.041,39.148,23.323,204.034,105.768,68.829,36.653,25.923,19.049,18.356,76.445
Total Mass Concentration,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Lref,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Lpwr,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Background Mixer,30.000,30.000,30.000,30.000,30.000,30.000,30.000,30.000,30.000,30.000,30.000,30.000,30.000,30.000,30.000,30.000
CPU Temperature,-1.000,-1.000,-1.000,-1.000,-1.000,-1.000,-1.000,-1.000,-1.000,-1.000,-1.000,-1.000,-1.000,-1.000,-1.000,-1.000
Display Temp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# export as a csv file
summer2022.to_csv('Summer_2022.csv')

### Summer 2021

In [3]:
# identify the directory as the "Raw_LISST_files" folder
directory = "Raw_LISST_files/Summer_2021"

# make a list of all the files in the directory
files = os.listdir(directory)

# create a list to store DataFrames
dfs = []

# iterate over the files
for file in files:
    # check if the file is an ASC file
    if file.endswith('.ASC'):
        # read the file
        data = pd.read_csv(directory + '/' + file, delimiter=',', skiprows=3)
        # transpose the data
        data_transposed = data.transpose()
        # convert the second column to a numeric type
        data_transposed.iloc[:, 1] = pd.to_numeric(data_transposed.iloc[:, 1], errors='coerce')
        # convert the second column to a DataFrame and set the column name to the file name
        df = data_transposed.iloc[:, 1].to_frame(name=os.path.splitext(file)[0])
        # add the DataFrame to the list
        dfs.append(df)

# concatenate all the DataFrames in the list into a single DataFrame
summer2021 = pd.concat(dfs, axis=1)

In [4]:
summer2021

                             REDOS1
Date                            NaN
 Time                           NaN
 Optical Transmission         0.800
 Total Volume Concentration  95.219
 Total Mass Concentration     0.000
...                             ...
 Battery Voltage              0.000
 Lref                         0.000
 Lpwr                         0.000
 Reserved                    30.000
 Reserved                    -1.000

[84 rows x 1 columns]

In [6]:
# Replace 'input_file.asc' with the path to your ASC file
input_file = 'Raw_LISST_files/Summer_2021/REDOS1.ASC'

# Read the entire ASC file without assuming any structure
with open(input_file, 'r') as file:
    data = file.readlines()

# Convert the file into a dataframe (one line per row)
summer_2021 = pd.DataFrame(data, columns=['Content'])

In [8]:
summer_2021

                                              Content
0   LISST-Portable Data File  Created on: Saturday...
1                LISST-Portable Serial number = 606\n
2       Firmware Version 3.013 Aug 10 2021 11:19:30\n
3   Date, Time, Optical Transmission, Total Volume...
4   MM/DD/YYYY, HH:MM:SS, %, ul/l, mg/l, microns, ...
5   02/12/2022, 11:31:37,     0.800,    95.219,   ...
6   02/12/2022, 11:32:45,     0.802,    90.857,   ...
7   02/12/2022, 11:33:38,     0.803,    89.344,   ...
8   02/12/2022, 11:34:35,     0.803,    88.157,   ...
9   02/12/2022, 11:35:33,     0.804,    86.296,   ...
10  02/12/2022, 11:50:45,     0.778,   114.278,   ...
11  02/12/2022, 11:51:45,     0.779,   102.572,   ...
12  02/12/2022, 11:52:36,     0.780,    97.892,   ...
13  02/12/2022, 11:53:43,     0.781,    91.618,   ...
14  02/12/2022, 11:55:49,     0.783,    87.238,   ...
15  02/12/2022, 12:05:21,     0.888,    50.929,   ...
16  02/12/2022, 12:06:27,     0.888,    43.833,   ...
17  02/12/2022, 12:07:22,     0.888,    43.498,   ...
18  02/12/2022, 12:08:21,     0.890,    36.327,   ...
19  02/12/2022, 12:10:01,     0.892,    33.730,   ...
20  02/12/2022, 12:19:21,     0.851,   101.071,   ...
21  02/12/2022, 12:20:32,     0.854,    80.254,   ...
22  02/12/2022, 12:21:30,     0.854,    71.744,   ...
23  02/12/2022, 12:23:05,     0.855,    66.348,   ...
24  02/12/2022, 12:24:06,     0.856,    62.067,   ...
25  02/12/2022, 12:30:35,     0.913,    92.061,   ...
26  02/12/2022, 12:31:42,     0.913,    78.126,   ...
27  02/12/2022, 12:32:35,     0.910,    97.962,   ...
28  02/12/2022, 12:33:34,     0.916,    67.113,   ...
29  02/12/2022, 12:34:35,     0.917,    59.462,   ...
30  02/12/2022, 12:54:07,     0.861,    95.686,   ...
31  02/12/2022, 12:55:03,     0.862,    87.636,   ...
32  02/12/2022, 12:56:00,     0.864,    82.154,   ...
33  02/12/2022, 12:57:02,     0.865,    77.595,   ...
34  02/12/2022, 12:57:58,     0.867,    72.230,   ...
35  02/12/2022, 13:08:11,     0.832,    89.666,   ...
36  02/12/2022, 13:09:06,     0.830,    82.389,   ...
37  02/12/2022, 13:12:25,     0.832,    77.001,   ...
38  02/12/2022, 13:13:43,     0.832,    75.118,   ...
39  02/12/2022, 13:16:09,     0.834,    70.085,   ...
40  02/12/2022, 13:27:14,     0.793,   124.049,   ...
41  02/12/2022, 13:28:27,     0.794,   102.211,   ...
42  02/12/2022, 13:29:32,     0.794,    92.984,   ...
43  02/12/2022, 13:30:46,     0.795,    86.999,   ...
44  02/12/2022, 13:31:43,     0.795,    82.030,   ...
45  02/12/2022, 13:36:12,     0.908,    65.296,   ...
46  02/12/2022, 13:37:10,     0.910,    54.566,   ...
47  02/12/2022, 13:38:04,     0.911,    48.924,   ...
48  02/12/2022, 13:39:39,     0.912,    45.411,   ...
49  02/12/2022, 13:40:30,     0.913,    40.838,   ...
50  02/12/2022, 13:45:17,     0.959,    42.867,   ...
51  02/12/2022, 13:46:14,     0.962,    33.957,   ...
52  02/12/2022, 13:47:28,     0.965,    23.610,   ...
53  02/12/2022, 13:48:18,     0.965,    19.859,   ...
54  02/12/2022, 13:51:10,     0.967,    16.756,   ...